erlixir:
  - otp-version: 27.3
    elixir-version: 1.18.2
    use-git: true
    git-repo: 'adiibanez/otp'
    git-ref: 'OTP-27.3-noiosminversion'

os: ['macos-latest']

platform:
  - id: 'macos_arm64'
    name: 'macOS arm64'
    sdk: 'macosx'
    arch: 'arm64'
    base_arch: 'macos'
    openssl_prefix: '_build/ios-openssl/build/openssl.macos.arm64'
    openssl_opts: 'no-ssl3 no-ssl3-method no-zlib'
    openssl_arch: 'darwin64-arm64'
    otp_arch: 'aarch64-apple-darwin'
    xcomp: 'aarch64-darwin'
    rust_target: 'aarch64-apple-darwin'

  - id: 'macos_x86_64'
    name: 'macOS x86_64'
    sdk: 'macosx'
    arch: 'x86_64'
    base_arch: 'macos'
    openssl_prefix: '_build/ios-openssl/build/openssl.macos.x86_64'
    openssl_opts: 'no-ssl3 no-ssl3-method no-zlib'
    openssl_arch: 'darwin64-x86_64'
    otp_arch: 'x86_64-apple-darwin'
    xcomp: 'x86_64-darwin'
    rust_target: 'x86_64-apple-darwin'
