erlixir:
  - otp_version: 27.3
    elixir_version: 1.18.2
    use_git: 'true'
    git_repo: 'adiibanez/otp'
    git_ref: 'OTP-27.3-noiosminversion'
    erl_opts_description: 'min;no-stripping;-year2038;-megaco'
    erl_opts: '--disable-stripped-runtime --disable-year2038 --disable-megaco-flex-scanner-lineno --disable-megaco-reentrant-flex-scanner --without-javac --without-odbc --without-wx --disable-sctp --disable-megaco --disable-corba'

platform:
  - platform_id: 'macos_arm64'
    name: 'macOS arm64'
    sdk: 'macosx'
    arch: 'arm64'
    base_arch: 'macos'
    openssl_prefix: '_build/ios-openssl/build/openssl.macos.arm64'
    openssl_opts: 'no-ssl3 no-ssl3-method no-zlib'
    openssl_arch: 'darwin64-arm64'
    otp_arch: 'aarch64-apple-darwin'
    xcomp: 'aarch64-darwin'
    rust_target: 'aarch64-apple-darwin'

  - platform_id: 'macos_x86_64'
    name: 'macOS x86_64'
    sdk: 'macosx'
    arch: 'x86_64'
    base_arch: 'macos'
    openssl_prefix: '_build/ios-openssl/build/openssl.macos.x86_64'
    openssl_opts: 'no-ssl3 no-ssl3-method no-zlib'
    openssl_arch: 'darwin64-x86_64'
    otp_arch: 'x86_64-apple-darwin'
    xcomp: 'x86_64-darwin'
    rust_target: 'x86_64-apple-darwin'
