FROM dockcross/android-arm:20250311-4bd0eec

ARG OTP_SOURCE=https://github.com/adiibanez/otp
ARG OTP_TAG=OTP-27.3-noiosminversion
# ENV
ENV NDK_ROOT $CROSS_ROOT
ENV ANDROID_NDK_HOME $CROSS_ROOT
ENV NDK_ABI_PLAT androideabi23
ENV PATH $NDK_ROOT/bin:$PATH
ENV FC= CPP= LD= CXX=clang++ CC=clang AR=ar
ENV MAKEFLAGS "-j10 -O"

# OpenSSL fails to detect this: 
RUN cp ${NDK_ROOT}/bin/llvm-ar ${NDK_ROOT}/bin/arm-linux-androideabi-ar
RUN cp ${NDK_ROOT}/bin/llvm-ranlib ${NDK_ROOT}/bin/arm-linux-androideabi-ranlib

# Setting up openssl
COPY scripts/install_openssl.sh /work/
COPY patch /work/patch

RUN echo ARCH="android-arm -D__ANDROID_API__=23" ./install_openssl.sh

# Fetching OTP
#RUN git clone --depth 1 https://github.com/adiibanez/otp _build/otp_cache/otp --branch OTP-27.3-noiosminversion
#COPY _build/otp_cache/otp_src_OTP-27.3-noiosminversion.tar.gz ./
# RUN tar -xzf otp_src_OTP-27.3-noiosminversion.tar.gz \
#     && mv otp_src_OTP-27.3-noiosminversion otp \
#     && rm otp_src_OTP-27.3-noiosminversion.tar.gz

RUN echo git clone $OTP_SOURCE --branch $OTP_TAG otp

ENV LIBS /usr/local/openssl/lib/libcrypto.a

# We need -z global for liberlang.so because:
# https://android-ndk.narkive.com/iNWj05IV/weak-symbol-linking-when-loading-dynamic-libraries
# https://android.googlesource.com/platform/bionic/+/30b17e32f0b403a97cef7c4d1fcab471fa316340/linker/linker_namespaces.cpp#100
ENV CFLAGS="-Os -fPIC" CXXFLAGS="-Os -fPIC" LDFLAGS="-z global" CXX= CC=

# RUN env
WORKDIR /work/otp

# Build with debugger produces
# dbg_wx_filedialog_win.erl:22: behaviour wx_object undefined

# Build run #1, building the x86 based cross compiler which will generate the .beam files


RUN ls -lah || true 
RUN ls -lah otp_build || true
RUN echo ./otp_build setup --disable-jit --with-ssl=/usr/local/openssl/ --disable-dynamic-ssl-lib --without-javac --without-odbc --without-wx --without-debugger --without-observer --without-cdv --without-et --xcomp-conf=xcomp/erl-xcomp-arm-android.conf  || bash -c 'cat erts/config.log && exit 1'
RUN echo ./otp_build boot -a

# Build run #2, now creating the arm binaries, appliying the install flags only here...
ENV echo INSTALL_PROGRAM "/usr/bin/install -c -s --strip-program=llvm-strip"
RUN echo ./otp_build configure --disable-jit --with-ssl=/usr/local/openssl/ --disable-dynamic-ssl-lib --without-javac --without-odbc --without-wx --without-debugger --without-observer --without-cdv --without-et --xcomp-conf=xcomp/erl-xcomp-arm-android.conf  LDFLAGS="-z global"
RUN echo ./otp_build release -a
