name: Build OpenSSL
on:
  workflow_call:
    inputs:
      matrix_json:
        required: true
        type: string

jobs:
  build-openssl:
    runs-on: macos-latest
    strategy:
      matrix: ${{ fromJson(inputs.matrix_json).platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Openssl Text matrix
        run: |
          echo ${{ inputs.matrix_json }}
          # echo ${{ env.OPENSSL_VERSION }} ${{ matrix.id }}

      # - name: Build OpenSSL ${{ env.OPENSSL_VERSION }} ${{ matrix.platform_id }}
      #   run: |
      #     MSG="Building ${{matrix.platform_id}} ${{ github.workflow }}"
      #     mkdir -p _build/${{matrix.platform_id}}_${{ github.workflow }}
      #     echo $MSG > _build/${{matrix.platform_id}}_${{ github.workflow }}/artifact.txt

      #     name: ${{matrix.platform_id}}_${{ github.workflow }}
      #     path: _build/${{matrix.platform_id}}_${{ github.workflow }}/

      # - name: Upload OpenSSL Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{matrix.platform_id}}_${{ github.workflow }}
      #     path: _build/${{matrix.platform_id}}_${{ github.workflow }}/
