name: Build Native NIFs
on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  build-nifs:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: ${{ fromJson(inputs.matrix).platform }}
        erlixir: ${{ fromJson(inputs.matrix).erlixir }}
        include: 
            - { nif_package_name: "NIF_Package_1", repo_count: 2, config: "config1" }
            - { nif_package_name: "NIF_Package_2", repo_count: 1, config: "config2" }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build NIFs ${{matrix.platform.id}} ${{ matrix.package.name }} ${{matrix.erlixir.otp-version}} ${{matrix.nif_package_name}}
        run: |
          MSG="Building ${{matrix.platform.id}} ${{ github.workflow }} ${{matrix.erlixir.otp-version}} ${{matrix.nif_package_name}}" 
          mkdir -p _build/${{matrix.platform.id}}_${{ github.workflow }}_${{matrix.erlixir.otp-version}}_${{matrix.nif_package_name}}
          echo $MSG > _build/${{matrix.platform.id}}_${{ github.workflow }}_${{matrix.erlixir.otp-version}}_${{matrix.nif_package_name}}/artifact.txt

      - name: Upload NIF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.platform.id}}_${{ github.workflow }}_${{matrix.erlixir.otp-version}}_${{matrix.nif_package_name}}
          path: _build/${{matrix.platform.id}}_${{ github.workflow }}_${{matrix.erlixir.otp-version}}_${{matrix.nif_package_name}}/
