name: Build OTP
on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string
      round:
        required: true
        type: number

jobs:
  build-otp:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: ${{ fromJson(inputs.matrix).platform }}
        erlixir: ${{ fromJson(inputs.matrix).erlixir }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build OTP Round ${{ inputs.round }}
        run: |
          MSG="Building ${{matrix.platform.id}} ${{ github.workflow }} ${{matrix.erlixir.otp-version}} ${{inputs.round}}" 
          mkdir -p _build/${{matrix.platform.id}}_${{ github.workflow }}_${{matrix.erlixir.otp-version}}_${{inputs.round}}
          echo $MSG > _build/${{matrix.platform.id}}_${{ github.workflow }}_${{matrix.erlixir.otp-version}}_${{inputs.round}}/artifact.txt

          name: ${{matrix.platform.id}}_${{ github.workflow }}_${{matrix.erlixir.otp-version}}_${{inputs.round}}
          path: _build/${{matrix.platform.id}}_${{ github.workflow }}_${{matrix.erlixir.otp-version}}_${{inputs.round}}/

      - name: Upload OTP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.platform.id}}_${{ github.workflow }}_${{matrix.erlixir.otp-version}}_${{inputs.round}}
          path: _build/${{matrix.platform.id}}_${{ github.workflow }}_${{matrix.erlixir.otp-version}}_${{inputs.round}}/
