name: Build OpenSSL
on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  build-openssl:
    runs-on: macos-latest
    steps:
      - name: Debug - Print Matrix Input
        run: |
          echo "Matrix input: ${{ inputs.matrix }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build OpenSSL
        run: |
          MSG="Building OpenSSL for ${{ matrix.platform_name }}"
          mkdir -p _build/ios-openssl/
          echo $MSG > _build/ios-openssl/msg.txt
          echo $MSG

      - name: Upload OpenSSL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openssl-${{ matrix.platform_id }}
          path: _build/ios-openssl/
