name: Build Native NIFs
on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: "Invalidate Cache (Dummy Step)"  # Force a new cache key
        uses: actions/cache@v4
        with:
          path: .github/workflows  # Cache something
          key: matrix-generation-${{ github.run_id }}
      - name: Generate Matrix
        id: set-matrix
        run: |
          if [ ! -f .github/workflows/nif_packages.json ]; then
            echo "Error: nif_packages.json not found!" >&2
            exit 1
          fi
          PACKAGES=$(cat .github/workflows/nif_packages.json)
          MATRIX=$(echo "$PACKAGES" | jq -c '.[] | .repos | .[] | {package: (.name), repo: ., config: (.config)}')
          if [ $? -ne 0 ]; then
            echo "Error: jq command failed!" >&2
            exit 1
          fi
          MATRIX_ARRAY=$(echo "[$MATRIX]" | jq -s .)
           if [ $? -ne 0 ]; then
            echo "Error: jq command failed!" >&2
            exit 1
          fi
          echo "matrix=$(echo "$MATRIX_ARRAY" | jq -c .)" >> "$GITHUB_OUTPUT"

  build-nifs:
    needs: generate-matrix
    runs-on: macos-latest # Or your desired runner
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build NIFs for ${{ matrix.package }} - ${{ matrix.repo }}
        run: |
          echo "Building NIF package ${{ matrix.package }} for repo ${{ matrix.repo }} with config ${{ matrix.config }}"
          mkdir -p "_build/nifs/${{ matrix.package }}/${{ matrix.repo }}"
          echo "Building NIF package ${{ matrix.package }} for repo ${{ matrix.repo }} with config ${{ matrix.config }}" > "_build/nifs/${{ matrix.package }}/${{ matrix.repo }}/msg.txt"
      - name: Upload NIF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nif-${{ matrix.package }}-${{ matrix.repo }}
          path: "_build/nifs/${{ matrix.package }}/${{ matrix.repo }}"