name: Build Native NIFs
on:
  workflow_call:
    inputs:
      otp_version:
        required: true
        type: string
      elixir_version:
        required: true
        type: string
      platform_id:
        required: true
        type: string
      name:
        required: true
        type: string
      sdk:
        required: true
        type: string
      arch:
        required: true
        type: string
      otp_arch:
        required: true
        type: string

jobs:
  build-nifs:
    env: 
      NAME: "build-nifs"
    runs-on: macos-latest
    strategy:
      matrix:
        repo:
        - package: "NIF_Package_1"
          name: "rustler_btleplug"
          repo: "adiibanez/rustler_btleplug"
          ldflag_config: "config1"
          ref: "main"

        - package: "NIF_Package_1"
          name: "rustler_btleplug"
          repo: "adiibanez/rustler_btleplug"
          ldflag_config: "config1"
          ref: "dev"

        - package: "NIF_Package_1"
          name: "rustler"
          repo: "adiibanez/rustler"
          ldflag_config: "config1"
          ref: "dev"
        
        - package: "NIF_Package_1"
          name: "wasmex"
          repo: "adiibanez/wasmex"
          ldflag_config: "config1"
          ref: "dev"

        - package: "NIF_Package_1"
          name: "rustler_extra"
          repo: "adiibanez/rustler_extra"
          ldflag_config: "config2"
          ref: "develop"

        - package: "NIF_Package_2"
          name: "rustler_something"
          repo: "adiibanez/rustler_something"
          ldflag_config: "config3"
          ref: "release"
        
        - package: "NIF_Package_2"
          name: "wasmex"
          repo: "adiibanez/wasmex"
          ldflag_config: "config1"
          ref: "dev"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Package Information
        run: |
          echo "Building package: ${{ matrix.repo.package }}"

      - name: Build NIFs ${{inputs.platform_id}} ${{ matrix.repo.package }} ${{inputs.otp_version}} ${{matrix.repo.name}} ${{matrix.repo.repo }}
        run: |
          echo ${{matrix.repo.repo}}
          MSG="Building ${{inputs.platform_id}} ${{ env.NAME }} ${{inputs.otp_version}} ${{matrix.repo.name}} ${{matrix.repo.repo}} ${{matrix.repo.ref}}" 
          mkdir -p _build/${{inputs.platform_id}}_${{ env.NAME }}_${{inputs.otp_version}}_${{matrix.repo.name}}_${{matrix.repo.repo }}
          echo $MSG > _build/${{inputs.platform_id}}_${{ env.NAME }}_${{inputs.otp_version}}_${{matrix.repo.name}}_${{matrix.repo.repo }}/artifact.txt

      - name: Upload NIF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.platform_id}}_${{ env.NAME }}_${{inputs.otp_version}}_${{matrix.repo.package}}
          path: _build/${{inputs.platform_id}}_${{ env.NAME }}_${{inputs.otp_version}}_${{matrix.repo.package}}/
