name: Build Native NIFs
on:
  workflow_call:
    inputs:
      parent_matrix:
        required: true
        type: string
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      combined_matrix: ${{ steps.combine-matrices.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: "Invalidate Cache (Dummy Step)"  # Keeping this for now, but you can remove it once everything is stable
        uses: actions/cache@v4
        with:
          path: .github/workflows
          key: matrix-generation-${{ github.run_id }}
      - name: Generate NIF Matrix
        id: generate-nif-matrix
        run: |
          if [ ! -f .github/workflows/nif_packages.json ]; then
            echo "Error: nif_packages.json not found!" >&2
            exit 1
          fi
          PACKAGES=$(cat .github/workflows/nif_packages.json)
          if [ -z "$PACKAGES" ]; then
            echo "Error: nif_packages.json is empty or could not be read!" >&2
            exit 1
          fi
          if ! echo "$PACKAGES" | jq -e . > /dev/null; then
            echo "Error: nif_packages.json contains invalid JSON!" >&2
            exit 1
          fi

          # *** THIS IS THE ACTUAL, CORRECT JQ COMMAND ***
          MATRIX=$(echo "$PACKAGES" | jq -c '.[] | { name: .name, config: .config, repos: .repos } | .repos[] | {package: .name, repo: ., config: .config}')
          if [ $? -ne 0 ]; then
            echo "Error: jq command failed! (1)" >&2
            exit 1
          fi

          MATRIX_ARRAY=$(echo "[$MATRIX]" | jq -s .)
          if [ $? -ne 0 ]; then
            echo "Error: jq command failed! (2)" >&2
            exit 1
          fi
          echo "nif_matrix=$(echo "$MATRIX_ARRAY" | jq -c .)" >> "$GITHUB_OUTPUT"

      - name: Combine Matrices
        id: combine-matrices
        run: |
          PARENT_MATRIX='${{ inputs.parent_matrix }}'
          NIF_MATRIX=$(echo "${{ steps.generate-nif-matrix.outputs.nif_matrix }}")

          # Corrected jq to iterate over both platforms and NIF entries
          COMBINED_MATRIX=$(echo "$PARENT_MATRIX" | jq --argjson nif "$NIF_MATRIX" -c '
            .platform[] as $p | $nif[] | {platform: $p, package: .package, repo: .repo, config: .config}
          ')
          echo "matrix=$(echo "[$COMBINED_MATRIX]" | jq -s .)" >> "$GITHUB_OUTPUT"

  build-nifs:
    needs: generate-matrix
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.combined_matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build NIFs for ${{ matrix.platform.name }} - ${{ matrix.package }} - ${{ matrix.repo }}
        run: |
          echo "Building NIF package ${{ matrix.package }} for repo ${{ matrix.repo }} with config ${{ matrix.config }} (Platform: ${{ matrix.platform.name }})"
          mkdir -p "_build/nifs/${{ matrix.platform.id }}/${{ matrix.package }}/${{ matrix.repo }}"
          echo "Building NIF package ${{ matrix.package }} for repo ${{ matrix.repo }} with config ${{ matrix.config }} (Platform: ${{ matrix.platform.name }})" > "_build/nifs/${{ matrix.platform.id }}/${{ matrix.package }}/${{ matrix.repo }}/msg.txt"

      - name: Upload NIF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nif-${{ matrix.platform.id }}-${{ matrix.package }}-${{ matrix.repo }}
          path: "_build/nifs/${{ matrix.platform.id }}/${{ matrix.package }}/${{ matrix.repo }}"