name: Build OpenSSL

on:
  workflow_call:
    inputs:
      # Define ALL the inputs that correspond to the `with` values in main.yml
      id:
        required: true
        type: string
      name:
        required: true
        type: string
      sdk:
        required: true
        type: string
      arch:
        required: true
        type: string
      base_arch:
        required: true
        type: string
      openssl_prefix:
        required: true
        type: string
      openssl_opts:
        required: true
        type: string
      openssl_arch:
        required: true
        type: string

jobs:
  build_openssl:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display Inputs (for debugging)
        shell: bash
        run: |
          echo "Platform ID: ${{ inputs.id }}"

      - name: Configure OpenSSL
        shell: bash
        run: |
          echo "Configuring OpenSSL for ${{inputs.arch}}..."

      # Example artifact creation/upload
      - name: Create Dummy Artifact
        shell: bash
        run: |
          mkdir -p _build/${{ inputs.id }}_${{ env.OPENSSL_VERSION}}
          echo "This is a dummy artifact for ${inputs.id} and (unused) OTP Version ${{ env.OPENSSL_VERSION }}" > _build/${{ inputs.id }}/artifact.txt
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.id }}_${{ env.OPENSSL_VERSION }}_openssl
          path: _build/${{ inputs.id }}_${{ env.OPENSSL_VERSION }}/
