name: Build OpenSSL
on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  build-openssl:
    runs-on: macos-latest
    strategy:
      matrix: 
        platform: ${{ fromJson(inputs.matrix).platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build OpenSSL ${{ env.OPENSSL_VERSION }} ${{ matrix.platform.id }}
        run: |
          MSG="Building ${{matrix.platform.id}} ${{ github.workflow }}" 
          mkdir -p _build/${{matrix.platform.id}}_${{ github.workflow }}
          echo $MSG > _build/${{matrix.platform.id}}_${{ github.workflow }}/artifact.txt

          name: ${{matrix.platform.id}}_${{ github.workflow }}
          path: _build/${{matrix.platform.id}}_${{ github.workflow }}/

      - name: Upload OpenSSL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.platform.id}}_${{ github.workflow }}
          path: _build/${{matrix.platform.id}}_${{ github.workflow }}/
