name: Build Native NIFs
on:
  workflow_call:
    inputs:
      platform_id:
        required: true
        type: string
      platform_name:
        required: true
        type: string
      platform_sdk:
        required: true
        type: string
      platform_arch:
        required: true
        type: string
      platform_rust_target:
        required: true
        type: string
      otp_version:
        required: true
        type: string
      elixir_version:
        required: true
        type: string
      nif_package_name:
        required: true
        type: string
      nif_package_config:
        required: true
        type: string
      nif_repo:
        required: true
        type: string

jobs:
  build-nifs:
    runs-on: macos-latest # You can define it here, if all builds run on the same OS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build NIFs
        run: |
          echo "Building NIF package ${{ inputs.nif_package_name }} for repo ${{ inputs.nif_repo }} with config ${{ inputs.nif_package_config }} (Platform: ${{ inputs.platform_name }})"
          mkdir -p "_build/nifs/${{ inputs.platform_id }}/${{ inputs.nif_package_name }}/${{ inputs.nif_repo }}"
          echo "Building NIF package ${{ inputs.nif_package_name }} for repo ${{ inputs.nif_repo }} with config ${{ inputs.nif_package_config }} (Platform: ${{ inputs.platform_name }})" > "_build/nifs/${{ inputs.platform_id }}/${{ inputs.nif_package_name }}/${{ inputs.nif_repo }}/msg.txt"

      - name: Upload NIF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nif-${{ inputs.platform_id }}-${{ inputs.nif_package_name }}-${{ inputs.nif_repo }}
          path: "_build/nifs/${{ inputs.platform_id }}/${{ inputs.nif_package_name }}/${{ inputs.nif_repo }}"