name: Debug Matrix Generation (Self-Contained)

on:
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      nif_matrix: ${{ steps.generate-nif-matrix.outputs.nif_matrix }}
    steps:
      - name: Generate NIF Matrix
        id: generate-nif-matrix
        shell: bash  # Explicitly use bash
        run: |
          # Inline the JSON for testing.  This eliminates file-related issues.
          PACKAGES='[
            { "name": "NIF_Package_1", "config": "config1", "repos": ["repo1", "repo2"] },
            { "name": "NIF_Package_2", "config": "config2", "repos": ["repo3"] }
          ]'

          echo "--- Debug: PACKAGES (inlined): ---"
          echo "$PACKAGES"
          echo "--- Debug: End of PACKAGES ---"


          # *** TRULY CORRECTED JQ COMMAND ***
          MATRIX=$(echo "$PACKAGES" | jq -c '.[] | { name: .name, config: .config, repos: .repos } | .repos[] | {package: .name, repo: ., config: .config}')
          if [ $? -ne 0 ]; then
            echo "Error: jq command failed! (1)" >&2
            echo "--- Debug: jq error output:" >&2
            echo "$PACKAGES" | jq -c '.[] | { name: .name, config: .config, repos: .repos } | .repos[] | {package: .name, repo: ., config: .config}' 2>&1
            exit 1
          fi
          echo "--- Debug: MATRIX:"
          echo "$MATRIX"

          MATRIX_ARRAY=$(echo "[$MATRIX]" | jq -s .)
          if [ $? -ne 0 ]; then
            echo "Error: jq command failed! (2)" >&2
            exit 1
          fi

          echo "nif_matrix=$(echo "$MATRIX_ARRAY" | jq -c .)" >> "$GITHUB_OUTPUT"

  debug-output:
    needs: generate-matrix
    runs-on: ubuntu-latest
    steps:
      - name: Print nif_matrix
        run: |
            echo "nif_matrix: ${{ needs.generate-matrix.outputs.nif_matrix }}"