name: "CI"
on: ["push", "pull_request"]
env:
  OTP_SOURCE: https://github.com/erlang/otp

jobs:
  build-android:
    strategy:
      fail-fast: false
      matrix:
        arch: ["arm", "arm64", "x86_64"]
        erlixir:
          - { otp-version: 27.2.4, elixir-version: 1.18.2 }
          - { otp-version: 26.2.5.6, elixir-version: 1.16.3 }
    env:
      OTP_TAG: OTP-${{ matrix.erlixir.otp-version }}
    name: "Build Android runtimes"
    runs-on: "ubuntu-latest"

    steps:
      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.erlixir.otp-version }}
          elixir-version: ${{ matrix.erlixir.elixir-version }}

      - name: Debug erlef/setup-beam install locations
        shell: bash
        run: |
          env | grep INSTALL_DIR_FOR_

      - uses: actions/checkout@v4

      - name: Build Android ${{ matrix.arch }} runtimes
        run: |
          mix deps.get
          ARCH=${{ matrix.arch }} mix package.android.runtime
          ARCH=${{ matrix.arch }} mix package.android.nif

      - name: Archive Android runtimes
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ matrix.arch }}-${{ matrix.erlixir.otp_version }}-${{ matrix.erlixir.elixir_version }}-runtime.zip
          path: _build/*.zip

      - name: Android ${{ matrix.arch }} release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: _build/*.zip

  build-ios:
    strategy:
      fail-fast: false
      matrix:
        erlixir:
          - { otp-version: 27.2.4, elixir-version: 1.18.2 }
          - { otp-version: 26.2.5.6, elixir-version: 1.16.3 }
    env:
      OTP_TAG: OTP-${{ matrix.erlixir.otp-version }}

    name: "Build iOS runtime"
    runs-on: "macos-latest"
    steps:
      - run: brew install git carthage coreutils
      - uses: actions/checkout@v4

      - name: Asdf Cache
        uses: actions/cache@v3
        id: asdf-cache
        with:
          path: /Users/runner/.asdf
          key: macos-asdf-${{ matrix.erlixir.otp-version }}-${{ matrix.erlixir.elixir-version }}

      - name: Setup asdf
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf

      - name: Setup elixir
        id: asdf-setup
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        run: |
          . $HOME/.asdf/asdf.sh
          asdf plugin add erlang
          asdf plugin add elixir
          echo "erlang 26.2.5.6" >> .tool-versions
          echo "elixir 1.16.3-otp-24" >> .tool-versions
          asdf install

      - name: Save asdf Cache
        if: steps.asdf-cache.outputs.cache-hit != 'true' && steps.asdf-setup.outcome == 'success'
        uses: actions/cache/save@v3
        with:
          path: |
            /Users/runner/.asdf
          key: macos-asdf-${{ matrix.erlixir.otp-version }}-${{ matrix.erlixir.elixir-version }}

      - name: Build iOS runtime
        run:  |
          . $HOME/.asdf/asdf.sh
          mix package.ios.runtime

      - name: Archive runtimes
        uses: actions/upload-artifact@v4
        with:
          name: ios-${{ matrix.erlixir.otp_version }}-${{ matrix.erlixir.elixir_version }}-runtime.xcframework.zip
          path: _build/liberlang.xcframework

      - name: iOS release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: _build/liberlang.xcframework