name: Combine OTP Builds
on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  final_combine:
    runs-on: macos-latest
    strategy:
      matrix: 
        erlixir: ${{ fromJson(inputs.matrix).erlixir }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download OTP Round 2 Artifacts
        uses: actions/download-artifact@v4
        with:
          path: _build/

      - name: Final Combination Step
        run: |
          MSG="Building ${{ github.workflow }}" 
          mkdir -p _build/${{matrix.erlixir.otp-version}}_${{ github.workflow }}
          echo $MSG > _build/${{matrix.erlixir.otp-version}}_${{ github.workflow }}/artifact.txt
          echo `find _build/ -type f`
          echo `find _build/ -type f` > _build/${{matrix.erlixir.otp-version}}_${{ github.workflow }}/artifact_list.txt

      - name: Upload Final Build
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.erlixir.otp-version}}_${{ github.workflow }}
          path: _build/${{matrix.erlixir.otp-version}}_${{ github.workflow }}/
