name: Dummy Apple OTP Build Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set Platform & OTP Matrix
        id: set-matrix
        run: |
          # Method 1: Use jq to ensure valid JSON and remove whitespace (Recommended)
          MATRIX=$(jq -c . .github/workflows/matrix.json)
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"

          # Method 2: Use tr to remove whitespace (Less Robust)
          # MATRIX=$(cat .github/workflows/matrix.json | tr -d '[:space:]')
          # echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"

          # Method 3: Use a multi-line string with a delimiter (Most Robust, but verbose)
          # cat << EOF >> "$GITHUB_OUTPUT"
          # matrix=$(cat .github/workflows/matrix.json)
          # EOF

  build_openssl:
    needs: define-matrix
    uses: ./.github/workflows/build_openssl.yml
    with:
      matrix: ${{ needs.define-matrix.outputs.matrix }}

  build_otp_round_1:
    needs: [define-matrix, build_openssl]
    uses: ./.github/workflows/build_otp.yml
    with:
      matrix: ${{ needs.define-matrix.outputs.matrix }}
      round: 1

  build_nifs:
    needs: define-matrix
    uses: ./.github/workflows/build_nifs.yml
    with:
      parent_matrix: ${{ needs.define-matrix.outputs.matrix }} 
    
  build_otp_round_2:
    needs: [build_otp_round_1, build_nifs]
    uses: ./.github/workflows/build_otp.yml
    with:
      matrix: ${{ needs.define-matrix.outputs.matrix }}
      round: 2

  final_combine:
    needs: build_otp_round_2
    runs-on: ubuntu-latest
    steps:
      - run: echo "Final combine (placeholder)"