name: Main Workflow

on:
  push:
    branches: dummy-ci
  workflow_dispatch:

jobs:
  load-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.read-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Read Matrix from JSON
        id: read-matrix
        run: |
          if [ ! -f .github/workflows/matrix_config.json ]; then
            echo "Error: matrix_config.json not found!" >&2
            exit 1
          fi
          MATRIX=$(jq -c . .github/workflows/matrix_config.json)
          if [ -z "$MATRIX" ]; then
            echo "Error: matrix_config.json is empty or could not be read!" >&2
            exit 1
          fi
          if ! echo "$MATRIX" | jq -e . > /dev/null; then
            echo "Error: matrix_config.json contains invalid JSON!" >&2
            exit 1
          fi
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
      - name: Debug - Print Matrix Output  # Keep this for debugging
        run: |
          echo "Matrix output: ${{ steps.read-matrix.outputs.matrix }}"

  build_openssl:
    needs: load-matrix
    uses: ./.github/workflows/build_openssl.yml
    with:
      matrix: ${{ needs.load-matrix.outputs.matrix }}

  build_otp_round_1:
    needs: [load-matrix, build_openssl]
    uses: ./.github/workflows/build_otp.yml
    with:
      matrix: ${{ needs.load-matrix.outputs.matrix }}
      round: 1

  build_nifs:
    needs: [load-matrix, build_otp_round_1]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.load-matrix.outputs.matrix) }}
    runs-on: macos-latest
    steps:
      - name: Call nifs workflow
        uses: ./.github/workflows/build_nifs.yml
        with:
          platform_id: ${{ matrix.platform_id }}
          platform_name: ${{ matrix.platform_name }}
          platform_sdk: ${{ matrix.platform_sdk }}
          platform_arch: ${{ matrix.platform_arch }}
          platform_rust_target: ${{ matrix.platform_rust_target }}
          otp_version: ${{ matrix.otp_version }}
          elixir_version: ${{ matrix.elixir_version }}
          nif_package_name: ${{ matrix.nif_package_name }}
          nif_package_config: ${{ matrix.nif_package_config }}
          nif_repo: ${{ matrix.nif_repo }}


  build_otp_round_2:
    needs: [build_otp_round_1, build_nifs]
    uses: ./.github/workflows/build_otp.yml
    with:
      matrix: ${{ needs.load-matrix.outputs.matrix }}
      round: 2

  final_combine:
    needs: build_otp_round_2
    runs-on: ubuntu-latest
    steps:
      - run: echo "Final combine (placeholder)"