name: Dummy Apple OTP Build Pipeline

on:
  push:
    # branches:
    #   - main
  pull_request:

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}  # This is correct
    steps:
      - name: Set Platform & OTP Matrix
        id: set-matrix
        run: |
          MATRIX=$(cat .github/workflows/matrix.json) # Read the file
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"

  build_openssl:
    needs: define-matrix
    strategy:   # This is the CRITICAL change: Use the matrix strategy
      matrix: ${{ fromJson(needs.define-matrix.outputs.matrix) }}
    uses: ./.github/workflows/build_openssl.yml
    with:
      version: ${{ matrix.erlixir.otp-version }}     # Pass values from the matrix
      # hash: ${{ matrix.erlixir.some_hash_value }}  # You'll need to define how to get the hash
      base_arch: ${{ matrix.platform.arch }}

  build_otp_round_1:
      needs: define-matrix # define-matrix! NOT build_openssl
      uses: ./.github/workflows/build_otp.yml
      strategy:  # Add strategy here too
        matrix: ${{ fromJson(needs.define-matrix.outputs.matrix) }}
      with:
        #Example of use:
        otp_version: ${{ matrix.erlixir.otp-version }}
        elixir_version: ${{ matrix.erlixir.elixir-version }}
        platform_id: ${{ matrix.platform.id }}
        platform_sdk: ${{ matrix.platform.sdk }}
        platform_arch: ${{ matrix.platform.arch }}
        round: 1

  build_nifs:
    needs: build_otp_round_1
    uses: ./.github/workflows/build_nifs.yml

  build_otp_round_2:
      needs: [build_otp_round_1, build_nifs]
      uses: ./.github/workflows/build_otp.yml
      strategy:  # And here
          matrix: ${{ fromJson(needs.define-matrix.outputs.matrix) }}
      with:
          #Example of use (same as above):
          otp_version: ${{ matrix.erlixir.otp-version }}
          elixir_version: ${{ matrix.erlixir.elixir-version }}
          platform_id: ${{ matrix.platform.id }}
          platform_sdk: ${{ matrix.platform.sdk }}
          platform_arch: ${{ matrix.platform.arch }}
          round: 2

  final_combine:
    needs: build_otp_round_2
    uses: ./.github/workflows/final_combine.yml